name: celluloid-snap
base: core22
adopt-info: celluloid-snap
summary: Simple GTK+ Frontend to MPV.
description: |
  Celluloid (formerly GNOME MPV) is a simple GTK+ frontend for mpv. It aims to be easy to use while maintaining high level of configurability. 
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
    
layout:
  /usr/local/bin/celluloid:
    symlink: $SNAP/usr/local/bin/celluloid
    
slots:
  celluloid-snap:
    interface: dbus
    bus: session
    name: io.github.CapeCrusader321.celluloid
 
                  
apps:
  celluloid-snap:
    command: usr/local/bin/celluloid
    extensions: [gnome]
    common-id: org.community.celluloid
    plugs:
      - home
      - audio-playback
      - alsa
      - pulseaudio
      - bluez
      - bluetooth-control
      - media-control
      - network
      - network-bind
      - raw-usb
      - optical-drive
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control
      
 
 
      
parts:
  celluloid-snap:
    source: https://github.com/celluloid-player/celluloid.git
    plugin: meson
    build-packages:
      - curl
      - build-essential
      - libgtk-4-1
      - libgtk-4-common
      - libgtk-4-dev
      - libc6
      - mpv
      - celluloid
      - libglib2.0-0
      - libmpv1
      - libmpv-dev
      - git
      
      
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
      curl -LO https://github.com/celluloid-player/celluloid/releases/download/v0.24/celluloid-0.24.tar.xz
    stage-packages:  
      - libmpv1
      - libavcodec-extra
      - libflite1
      - libavfilter-extra
      - libblas3
      - ocl-icd-libopencl1
      - libsdl2-2.0-0
      - libxss1
      - ffmpeg
      - libxv1
      - libaom3
      - libavdevice58
      - libavformat-extra
      - libavutil56
      - libbluray2
      - libbs2b0
      - libcdio19
      - libcdio-cdda2
      - libcdio-paranoia2
      - libchromaprint1
      - libcodec2-1.0
      - libdav1d5
      - libdc1394-25
      - libdecor-0-0
      - libdvdnav4
      - libdvdread8
      - libsmbclient
      - samba
     
    
     
     
   
  
  
