name: celluloid-snap
base: core22
version: 'v0.25'
summary: Simple GTK+ Frontend to MPV.
description: |
  Celluloid (formerly GNOME MPV) is a simple GTK+ frontend for mpv. It aims to be easy to use while maintaining high level of configurability. 
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
    
slots:
  mpris:
    interface: mpris
    name: org.mpris.MediaPlayer2.io.github.celluloid_player.Celluloid
    
  celluloid-snap:
    interface: dbus
    bus: session
    name: io.github.celluloid_player.Celluloid


apps:
  celluloid-snap:
    command: usr/bin/celluloid
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/blas:$SNAP/usr/lib/x86_64-linux-gnu/lapack:$SNAP/usr/lib/x86_64-linux-gnu
    extensions: [gnome]
    plugs:
      - home
      - audio-playback
      - media-control
      - network
      - network-bind
      - network-status
      - process-control
      - hostname-control
      - optical-drive
      - screen-inhibit-control
   
parts:  
  libadwaita:
    source: https://gitlab.gnome.org/GNOME/libadwaita.git
    source-tag: '1.3.1'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Ddebug=true
      - -Dintrospection=enabled
      - -Dvapi=true
      - -Dtests=false
      - -Dexamples=false
    build-packages:
      - sassc
    override-pull: |
      craftctl default
      sed -e 's/-W\(format-nonliteral\)\b/-Wno-\1/g' -i meson.build
    prime:
      - usr/lib/*/*adw*
      - usr/lib/*/*/Adw*  
  
  celluloid-snap:
    source: https://github.com/celluloid-player/celluloid.git
    after: [libadwaita, ffmpeg]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - curl
      - build-essential
      - libmpv-dev
      - appstream-util
      - autoconf-archive
      - libepoxy-dev
      - libgtk-4-dev
      - pkg-config
      - python3
      - luajit
      
    override-pull: |
      craftctl default
      curl -LO https://github.com/celluloid-player/celluloid/releases/download/v0.25/celluloid-0.25.tar.xz
  #craftctl set version=$(git describe --tags --abbrev=0)
    stage-packages:  
      - libv4l-0
      - libv4l2rds0
      - libv4lconvert0
      - libass9
      - libmpv1
      - libffmpeg-nvenc-dev
      - libblas3
      - liblapack3
    
  ffmpeg:
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
    autotools-configure-parameters:
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-gnutls
      - --enable-shared
      - --enable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
      - --enable-libaom
      - --enable-libass
      - --enable-libfdk-aac 
      - --enable-libfreetype 
      - --enable-libmp3lame 
      - --enable-libopus 
      - --enable-libsvtav1 
      - --enable-libdav1d
      - --enable-libvpx 
      - --enable-libx264 
      - --enable-libx265 
      - --enable-nonfree
        
    build-packages:
      - nasm
      - libgnutls28-dev
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    stage:
      - -usr/include
