name: celluloid-snap
base: core22
adopt-info: celluloid-snap
summary: Celluloid (formerly GNOME MPV) is a simple GTK+ frontend for mpv. It aims to be easy to use while maintaining high level of configurability. 
description: |
  Simple Libadwaita frontend to MPV.
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
    
    
    
                
apps:
  celluloid-snap:
    command: usr/bin/celluloid
    extensions: [gnome]
    common-id: org.community.celluloid
    plugs:
      - home
      - audio-playback
      - alsa
      - pulseaudio
      - bluez
      - bluetooth-control
      - media-control
      - network
      - network-bind
      - raw-usb
      - optical-drive
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control
      
 
 
      
parts:
  celluloid-snap:
    source: https://github.com/celluloid-player/celluloid.git
    plugin: meson
    build-packages:
      - curl
      - build-essential
      - libgtk-4-1
      - libgtk-4-common
      - libgtk-4-dev
      - libc6
      - libglib2.0-0
      - libmpv2
      - git
      
      
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags)
      
      
    
   
  
  
