name: celluloid-snap
base: core22
version: '0.25'
adopt-info: celluloid-snap
grade: stable
icon: snap/gui/gnome-mpv.svg
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
slots:
  celluloid-snap:
    interface: dbus
    bus: session
    name: io.github.celluloid_player.Celluloid


apps:
  celluloid-snap:
    command: usr/bin/celluloid
#    environment:
#      TMPDIR: $XDG_RUNTIME_DIR
#      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/blas:$SNAP/usr/lib/x86_64-linux-gnu/lapack:$SNAP/usr/lib/x86_64-linux-gnu
    extensions: [gnome]
    desktop: [usr/share/applications/io.github.celluloid_player.Celluloid.desktop]
    common-id: io.github.celluloid_player.Celluloid 
    plugs:
      - home
      - audio-playback
      - media-control
      - network
      - network-bind
      - network-status
      - process-control
      - hostname-control
      - optical-drive
      - screen-inhibit-control
    slots:
      - mpris

parts:
  mpv:
    source: https://github.com/mpv-player/mpv.git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dlibmpv=true
    build-packages:
      - curl
      - libavcodec-dev
      - libavfilter-dev
      - libass-dev
      - libx264-dev
      - libvorbis-dev
      - libjpeg-turbo8-dev
    prime:
      - usr/lib/*/libmpv*
  celluloid-snap:
    source: https://github.com/celluloid-player/celluloid.git
    after: [mpv]
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - autoconf-archive
      - libepoxy-dev
      - luajit
    stage-snaps:
      - ffmpeg
    stage-packages:  
      - libv4l-0
      - libv4l2rds0
      - libv4lconvert0
      - liblapack3
      - libblas3
      - libffmpeg-nvenc-dev
    parse-info: [usr/share/metainfo/io.github.celluloid_player.Celluloid.appdata.xml]
  cleanup:
    after: [celluloid-snap, mpv]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
