name: celluloid-snap
base: core22
version: 'v0.25'
summary: Simple GTK+ Frontend to MPV.
description: |
  Celluloid (formerly GNOME MPV) is a simple GTK+ frontend for mpv. It aims to be easy to use while maintaining high level of configurability. 
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
    
slots:
  mpris:
    interface: mpris
    name: org.mpris.MediaPlayer2.io.github.celluloid_player.Celluloid
    
  celluloid-snap:
    interface: dbus
    bus: session
    name: io.github.celluloid_player.Celluloid


apps:
  celluloid-snap:
    command: usr/bin/celluloid
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/blas:$SNAP/usr/lib/x86_64-linux-gnu/lapack:$SNAP/usr/lib/x86_64-linux-gnu
    extensions: [gnome]
    plugs:
      - home
      - audio-playback
      - media-control
      - network
      - network-bind
      - network-status
      - process-control
      - hostname-control
      - optical-drive
      - screen-inhibit-control
   
parts:  
  mpv:
    source: https://github.com/mpv-player/mpv.git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dlibmpv=true
    build-packages:
      - curl
      - libavcodec-dev
      - libavfilter-dev
      - libass-dev
      - libx264-dev
      - libvorbis-dev
      - libjpeg-turbo8-dev
    prime:
      - usr/lib/*/libmpv*
      
  celluloid-snap:
    source: https://github.com/celluloid-player/celluloid.git
    after: [ffmpeg, mpv]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - curl
      - build-essential
      - libmpv-dev
      - appstream-util
      - autoconf-archive
      - libepoxy-dev
      - libgtk-4-dev
      - pkg-config
      - python3
      - luajit
      
    override-pull: |
      craftctl default
      curl -LO https://github.com/celluloid-player/celluloid/releases/download/v0.25/celluloid-0.25.tar.xz
  #craftctl set version=$(git describe --tags --abbrev=0)
    stage-packages:  
      - libv4l-0
      - libv4l2rds0
      - libv4lconvert0
      - libass9
      - libffmpeg-nvenc-dev
      - libblas3
      - liblapack3
      
  ffmpeg:
    # WORKAROUND:
    # Build from source because the ffmpeg package installs libraries as dependencies
    # that conflict with the Gnome extension
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
    source-checksum: sha256/57be87c22d9b49c112b6d24bc67d42508660e6b718b3db89c44e47e289137082
    autotools-configure-parameters:
      # WORKAROUND: Install to /usr instead of /usr/local because it's not in search paths
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --enable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
    build-packages:
      - nasm
      - libgnutls28-dev
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    stage:
      - -usr/include  
      
 # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [celluloid-snap, ffmpeg]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
