name: celluloid-snap
base: core22
version: 'v0.24'
summary: Simple GTK+ Frontend to MPV.
description: |
  Celluloid (formerly GNOME MPV) is a simple GTK+ frontend for mpv. It aims to be easy to use while maintaining high level of configurability. 
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
    
layout:
  /usr/bin/celluloid:
    symlink: $SNAP/usr/bin/celluloid
    
slots:
  celluloid-snap:
    interface: dbus
    bus: session
    name: io.github.CapeCrusader321.celluloid
 
                  
apps:
  celluloid-snap:
    command: usr/bin/celluloid
    extensions: [gnome]
    common-id: org.community.celluloid
    plugs:
      - home
      - audio-playback
      - alsa
      - pulseaudio
      - bluez
      - bluetooth-control
      - media-control
      - network
      - network-bind
      - raw-usb
      - optical-drive
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control
      
 
 
      
parts:
  celluloid-snap:
    source: https://github.com/celluloid-player/celluloid.git
    plugin: meson
    meson-parameters: 
      - --prefix=/usr
    build-packages:
      - curl
      - build-essential
      - libgtk-4-1
      - libgtk-4-common
      - libgtk-4-dev
      - libc6
      - libglib2.0-0
      - libmpv1
      - libmpv-dev
      - libc6
      - libcairo2
      - libpangocairo-1.0-0
      - libpango-1.0-0
      - libepoxy0
      - gsettings-backend
      - youtube-dl
      - libadwaita-1-0
      - libblas3
      - ffmpeg
      - libv4l-0
      - libv4l2rds0
      - libv4lconvert0
      - libass9
      - uchardet
      - libuchardet0
      - luajit
      - libffmpeg-nvenc-dev
      
      
      
    override-pull: |
      craftctl default
      curl -LO https://github.com/celluloid-player/celluloid/releases/download/v0.24/celluloid-0.24.tar.xz
  #craftctl set version=$(git describe --tags --abbrev=0)
    
     
    
     
     
   
  
  
